### ISSUE TITLE
Float divison by zero error

### ISSUE THREAD

**Issue by sethyo7** [3b1b/videos#38]
Whenever I run certain scenes on scenes.py for wordle I get a float division by zero error.  This is what happens when I try to run scene 78: 
![Screenshot 2_13_2022 5_54_50 PM](https://user-images.githubusercontent.com/99512780/153779022-b2c038ad-e36d-4a4a-8508-620735b0b5ae.png)
`

**Comment by 3b1b** [comment]
The scene ordering probably changed since you submitted this, can you share the name of the relevant scene?

**Comment by sethyo7** [comment]
Im having the same problem. It is scene 76 now called  "WrapperForEntropyCalculation"

**Comment by 3b1b** [comment]
Ah, a few things seem amiss then.  I suspect something about how it's rendering LaTeX isn't working right, since what should be a bit of Text is treated as an empty object. This did expose a bug in the Write animation, though, which should now be fixed on the master branch of manimgl.

Also, for what it's worth, it really doesn't matter to run that scene, it's just a frame with text and nothing exciting.

**Comment by sethyo7** [comment]
oh ok thx. Is there a scene where i can input information and see how it does against actual games or is it just playing against what the word the code generates. I want to try against absurble like you did at the end of the video.

**Comment by 3b1b** [comment]
Sure, try ExternalPatternEntry, and use "0", "1" and "2" to enter colors after you enter the word.

**Comment by sethyo7** [comment]
It worked! Thank you for all the help.
